import type { ConsoleChallenge, DataSkill, EvalCriterion } from "../../types/consoleLab";
import { has, hasAny } from "../../utils/consoleLabEvaluator";
import { withApproaches } from "./approachTemplates";

function inferDataSkill(id: string, prompt: string): DataSkill {
  if (/HttpClient|GET https|api\./i.test(prompt)) return "json-api";
  if (/ReadLine|stdin|1-100|1–100/i.test(prompt + id)) return "stdin";
  if (/JSON file|\.json/i.test(prompt)) return "json-file";
  if (/CSV|csv|Split|columns/i.test(prompt)) return "csv";
  return "mixed";
}

function c(
  partial: Omit<
    ConsoleChallenge,
    "thoughtProcess" | "skeleton" | "criteria" | "commonMistakes" | "approaches" | "dataSkill"
  > & {
    think: [string, string][];
    skeleton: string[];
    criteria: EvalCriterion[];
    mistakes: string[];
    dataSkill?: DataSkill;
  },
): ConsoleChallenge {
  const dataSkill = partial.dataSkill ?? inferDataSkill(partial.id, partial.prompt);
  return withApproaches({
    ...partial,
    dataSkill,
    thoughtProcess: partial.think.map(([title, body], i) => ({
      step: i + 1,
      title,
      body,
    })),
    skeleton: partial.skeleton,
    criteria: partial.criteria,
    commonMistakes: partial.mistakes,
  });
}

export const MORE_CONSOLE_CHALLENGES: ConsoleChallenge[] = [
  c({
    id: "csv-sales-by-region",
    title: "Top 5 Regions by Total Sales",
    source: "Console Lab",
    difficulty: "junior",
    timeMinutes: 25,
    prompt: "CSV: Region,Amount. Sum sales per region, print top 5 regions descending. No external libs.",
    constraints: ["Console", "LINQ OK", "decimal for money"],
    think: [
      ["Read & split", "ReadAllLines, split comma, parse amount with TryParse, skip bad rows."],
      ["Aggregate", "Dictionary region→sum OR GroupBy + Sum."],
      ["Rank", "OrderByDescending total, Take(5), print."],
    ],
    skeleton: ["read csv", "sum by region", "top 5 print"],
    criteria: [
      { id: "read", label: "Reads file/lines", hint: "File.Read*", test: has(/File\.Read/i), weight: 1 },
      { id: "sum", label: "Sums per region", hint: "GroupBy/Sum or Dictionary", test: hasAny(/GroupBy/i, /Dictionary/i), weight: 2 },
      { id: "top5", label: "Top 5 descending", hint: "Take(5)", test: has(/Take\s*\(\s*5\s*\)/), weight: 1 },
    ],
    mistakes: ["Using average instead of sum", "Not skipping invalid amounts"],
  }),
  c({
    id: "json-users-avg-age",
    title: "Average Age by Country (JSON API)",
    source: "Console Lab",
    difficulty: "mid",
    timeMinutes: 30,
    prompt: "Fetch JSON users array with country and age. Print average age per country, sorted by country name A-Z.",
    constraints: ["HttpClient", "System.Text.Json"],
    think: [
      ["Fetch", "GET JSON, try/catch."],
      ["Parse", "Loop users, extract country + age."],
      ["Average", "Group by country, Average(age)."],
      ["Sort", "OrderBy country name."],
    ],
    skeleton: ["GET", "parse users", "group avg", "sort print"],
    criteria: [
      { id: "http", label: "HttpClient", hint: "GetStringAsync", test: has(/HttpClient/i), weight: 1 },
      { id: "json", label: "JSON parse", hint: "JsonDocument", test: has(/JsonDocument/i), weight: 1 },
      { id: "avg", label: "Average", hint: "Average()", test: has(/Average/i), weight: 2 },
      { id: "group", label: "Group by country", hint: "GroupBy", test: has(/GroupBy/i), weight: 1 },
    ],
    mistakes: ["Integer division for average", "Not handling missing age"],
  }),
  c({
    id: "log-ip-counts",
    title: "Log Parser — Requests per IP",
    source: "Console Lab",
    difficulty: "mid",
    timeMinutes: 30,
    prompt: "Parse log lines IP|timestamp|path. Count requests per IP, print top 10 IPs.",
    constraints: ["Split parsing", "Dictionary count"],
    think: [
      ["Format", "Identify IP as first field before delimiter."],
      ["Count", "Dictionary IP→count increment."],
      ["Top 10", "Sort by count desc."],
    ],
    skeleton: ["read lines", "split ip", "count", "top 10"],
    criteria: [
      { id: "split", label: "Splits log lines", hint: "Split('|') or similar", test: has(/Split/i), weight: 1 },
      { id: "dict", label: "Counts per IP", hint: "Dictionary", test: has(/Dictionary/i), weight: 2 },
      { id: "top", label: "Top 10", hint: "Take(10)", test: has(/Take\s*\(\s*10\s*\)/), weight: 1 },
    ],
    mistakes: ["Not trimming fields", "Counting wrong column"],
  }),
  c({
    id: "word-frequency",
    title: "Top 10 Word Frequency",
    source: "Console Lab",
    difficulty: "junior",
    timeMinutes: 25,
    prompt: "Read text file, count word frequency (case-insensitive), print top 10 words.",
    constraints: ["File read", "No external libs"],
    think: [
      ["Tokenize", "Split on whitespace/punctuation, ToLowerInvariant."],
      ["Count", "Dictionary word→count."],
      ["Rank", "OrderByDescending count, ThenBy word."],
    ],
    skeleton: ["read text", "tokenize lower", "count", "top 10"],
    criteria: [
      { id: "read", label: "Reads file", hint: "ReadAllText/ReadLines", test: has(/File\.Read/i), weight: 1 },
      { id: "lower", label: "Case insensitive", hint: "ToLower", test: hasAny(/ToLower/i), weight: 1 },
      { id: "count", label: "Word counts", hint: "Dictionary", test: has(/Dictionary/i), weight: 2 },
    ],
    mistakes: ["Including empty strings", "Not normalizing case"],
  }),
  c({
    id: "temp-monthly-avg",
    title: "Monthly Average Temperature",
    source: "Console Lab",
    difficulty: "mid",
    timeMinutes: 30,
    prompt: "CSV Date,Temperature. Average temp per month-year, print sorted chronologically.",
    constraints: ["DateTime parse", "GroupBy month"],
    think: [
      ["Parse date", "DateTime.TryParse on date column."],
      ["Key", "(Year, Month) grouping key."],
      ["Average", "Average temperature per group."],
      ["Sort", "Year then month."],
    ],
    skeleton: ["parse dates", "group month", "avg", "sort print"],
    criteria: [
      { id: "date", label: "Parses dates", hint: "DateTime", test: has(/DateTime/i), weight: 2 },
      { id: "group", label: "Groups by month", hint: "GroupBy/Year/Month", test: hasAny(/GroupBy/i, /\.Month/i), weight: 2 },
      { id: "avg", label: "Average", hint: "Average()", test: has(/Average/i), weight: 1 },
    ],
    mistakes: ["Grouping only by month without year"],
  }),
  c({
    id: "duplicate-emails",
    title: "Find Duplicate Emails in CSV",
    source: "Console Lab",
    difficulty: "junior",
    timeMinutes: 20,
    prompt: "CSV with Email column. Print emails that appear more than once.",
    constraints: ["HashSet or Dictionary"],
    think: [
      ["Count", "Dictionary email→count or track seen duplicates."],
      ["Filter", "Where count > 1."],
      ["Print", "One email per line."],
    ],
    skeleton: ["read emails", "count", "filter >1", "print"],
    criteria: [
      { id: "count", label: "Counts occurrences", hint: "Dictionary++", test: has(/Dictionary/i), weight: 2 },
      { id: "filter", label: "Filters duplicates", hint: "> 1 or similar", test: hasAny(/>\s*1/, /Count\s*>\s*1/i), weight: 1 },
    ],
    mistakes: ["Printing on first duplicate only once incorrectly"],
  }),
  c({
    id: "fizzbuzz-extended",
    title: "FizzBuzz 1–100 (Buzz on 7)",
    source: "Console Lab",
    difficulty: "junior",
    timeMinutes: 15,
    prompt: "1-100: Fizz if div 3, Buzz if div 5, FizzBuzz both, also Buzz if div 7. Print one per line.",
    constraints: ["Console loop", "No input file"],
    think: [
      ["Loop", "for i 1..100"],
      ["Rules", "Build string: check 3,5,7 in order; if empty print number."],
      ["Order", "Check combined before single labels if needed."],
    ],
    skeleton: ["for 1..100", "mod checks", "print line"],
    criteria: [
      { id: "loop", label: "Loop 1-100", hint: "for loop", test: has(/for\s*\(/i), weight: 1 },
      { id: "mod", label: "Modulo checks", hint: "% 3 or % 5", test: hasAny(/%\s*3/, /%\s*5/, /%\s*7/), weight: 2 },
      { id: "print", label: "Console output", hint: "WriteLine", test: has(/Console\.WriteLine/i), weight: 1 },
    ],
    mistakes: ["else-if chain missing FizzBuzz", "Forgetting div 7 rule"],
  }),
  c({
    id: "primes-to-n",
    title: "Prime Numbers up to N",
    source: "Console Lab",
    difficulty: "mid",
    timeMinutes: 25,
    prompt: "Read N from args or stdin. Print all primes <= N.",
    constraints: ["Efficient enough for N=10000"],
    think: [
      ["Input", "Parse int N, validate."],
      ["Sieve or trial", "Trial division with sqrt limit, or Sieve of Eratosthenes."],
      ["Output", "Space or line separated."],
    ],
    skeleton: ["read N", "isPrime/sieve", "print primes"],
    criteria: [
      { id: "input", label: "Reads N", hint: "args or Console.ReadLine", test: hasAny(/args/i, /ReadLine/i), weight: 1 },
      { id: "prime", label: "Prime logic", hint: "loop sqrt or sieve bool[]", test: hasAny(/Math\.Sqrt/i, /isPrime/i, /sieve/i), weight: 2 },
    ],
    mistakes: ["Treating 1 as prime", "O(n²) without mentioning for large N"],
  }),
  c({
    id: "palindrome-sentence",
    title: "Sentence Palindrome Checker",
    source: "Console Lab",
    difficulty: "junior",
    timeMinutes: 15,
    prompt: "Read line from stdin. Ignore spaces/punctuation/case. Print if palindrome.",
    constraints: ["Char filtering", "Two-pointer optional"],
    think: [
      ["Normalize", "Keep only letters, lower case."],
      ["Check", "Compare to reverse OR two pointers inward."],
      ["Output", "Yes/No or True/False."],
    ],
    skeleton: ["read line", "filter alnum lower", "compare reverse", "print"],
    criteria: [
      { id: "read", label: "Reads input", hint: "ReadLine", test: has(/ReadLine/i), weight: 1 },
      { id: "normalize", label: "Strips/normalizes", hint: "char.IsLetter/ToLower", test: hasAny(/IsLetter/i, /ToLower/i), weight: 1 },
      { id: "check", label: "Palindrome check", hint: "reverse or two-pointer", test: hasAny(/Reverse/i, /while/i), weight: 2 },
    ],
    mistakes: ["Not ignoring punctuation", "Case sensitive compare"],
  }),
  c({
    id: "bank-running-balance",
    title: "Running Balance from Transactions",
    source: "Console Lab",
    difficulty: "mid",
    timeMinutes: 25,
    prompt: "CSV Date,Type,Amount (Credit/Debit). Print running balance after each row.",
    constraints: ["decimal", "Ordered by date"],
    think: [
      ["Parse", "Amount as decimal, Type determines sign."],
      ["Running", "balance += credit, balance -= debit."],
      ["Print", "Each line shows balance after transaction."],
    ],
    skeleton: ["read rows", "decimal balance", "apply credit/debit", "print each"],
    criteria: [
      { id: "decimal", label: "decimal for money", hint: "decimal type", test: has(/decimal/i), weight: 1 },
      { id: "running", label: "Running total", hint: "+= in loop", test: hasAny(/\+=/, /balance/i), weight: 2 },
    ],
    mistakes: ["double rounding", "Wrong sign for debit"],
  }),
  c({
    id: "json-join-orders",
    title: "Join Users with Order Totals",
    source: "Console Lab",
    difficulty: "senior",
    timeMinutes: 35,
    prompt: "Two JSON arrays: users (id,name), orders (userId,total). Print name + sum of orders per user.",
    constraints: ["In-memory join", "System.Text.Json"],
    think: [
      ["Load both", "Parse two arrays or one response with both."],
      ["Join", "Group orders by userId, sum totals."],
      ["Lookup", "Match user id to name, left join missing users."],
    ],
    skeleton: ["parse users", "parse orders", "group sum", "join names print"],
    criteria: [
      { id: "json", label: "JSON parsing", hint: "JsonDocument", test: has(/JsonDocument/i), weight: 1 },
      { id: "join", label: "Join/group logic", hint: "GroupBy userId", test: hasAny(/GroupBy/i, /Join/i, /Dictionary/i), weight: 2 },
      { id: "sum", label: "Sum totals", hint: "Sum()", test: has(/Sum/i), weight: 1 },
    ],
    mistakes: ["N+1 lookup per order", "Missing users with zero orders"],
  }),
  c({
    id: "api-pagination-total",
    title: "Paginated API — Total Item Count",
    source: "Console Lab",
    difficulty: "senior",
    timeMinutes: 40,
    prompt: "API returns { results:[], next:url }. Loop pages until next is null, count all items.",
    constraints: ["while next", "HttpClient"],
    think: [
      ["First page", "GET initial URL."],
      ["Loop", "While next link not null, GET next, accumulate count."],
      ["Parse", "Count results length each page."],
    ],
    skeleton: ["GET page", "count results", "follow next", "sum print"],
    criteria: [
      { id: "loop", label: "Pagination loop", hint: "while next", test: hasAny(/while\s*\(/i, /next/i), weight: 2 },
      { id: "http", label: "HttpClient", hint: "GetStringAsync", test: has(/HttpClient/i), weight: 1 },
      { id: "results", label: "Reads results", hint: "results array", test: has(/results/i), weight: 1 },
    ],
    mistakes: ["Infinite loop on next", "Not handling empty results"],
  }),
  c({
    id: "stock-max-gain",
    title: "Max Daily Gain per Stock Symbol",
    source: "Console Lab",
    difficulty: "mid",
    timeMinutes: 30,
    prompt: "CSV Symbol,Date,Open,Close. For each symbol find day with max (Close-Open), print symbol and gain.",
    constraints: ["GroupBy symbol", "decimal"],
    think: [
      ["Parse", "decimal Open/Close per row."],
      ["Gain", "Close - Open per row."],
      ["Max per symbol", "GroupBy Symbol, OrderByDescending gain, First."],
    ],
    skeleton: ["read csv", "compute gain", "max per symbol", "print"],
    criteria: [
      { id: "gain", label: "Computes gain", hint: "Close - Open", test: hasAny(/Close\s*-/, /gain/i), weight: 2 },
      { id: "group", label: "Per symbol", hint: "GroupBy", test: has(/GroupBy/i), weight: 1 },
    ],
    mistakes: ["Max across all stocks instead of per symbol"],
  }),
  c({
    id: "anagram-groups",
    title: "Group Anagrams",
    source: "Console Lab",
    difficulty: "mid",
    timeMinutes: 30,
    prompt: "Read words from file. Group anagrams together, print each group on one line.",
    constraints: ["Key = sorted chars", "Dictionary"],
    think: [
      ["Key", "Sort letters of word → canonical key."],
      ["Group", "Dictionary key → list of words."],
      ["Print", "Each group joined."],
    ],
    skeleton: ["read words", "sort chars key", "dict lists", "print groups"],
    criteria: [
      { id: "key", label: "Anagram key", hint: "OrderBy chars or Sort char[]", test: hasAny(/OrderBy/i, /Sort/i), weight: 2 },
      { id: "dict", label: "Grouping", hint: "Dictionary/List", test: has(/Dictionary/i), weight: 1 },
    ],
    mistakes: ["Using raw word as key", "Case sensitivity"],
  }),
  c({
    id: "roman-numeral",
    title: "Integer to Roman Numeral",
    source: "Console Lab",
    difficulty: "mid",
    timeMinutes: 25,
    prompt: "Read int 1-3999, print Roman numeral.",
    constraints: ["Greedy subtract table"],
    think: [
      ["Table", "Pairs (value, symbol) descending: 1000 M, 900 CM..."],
      ["Greedy", "While n>=value append symbol, subtract."],
      ["Edge", "Validate range."],
    ],
    skeleton: ["read int", "value-symbol pairs", "greedy loop", "print"],
    criteria: [
      { id: "table", label: "Symbol mapping", hint: "M,D,C,L,X,V,I or pairs array", test: hasAny(/1000/, /"M"/, /values/i), weight: 2 },
      { id: "loop", label: "Build string", hint: "while/for subtract", test: hasAny(/while/i, /for/i), weight: 1 },
    ],
    mistakes: ["Missing subtractive forms IV, IX, CM"],
  }),
  c({
    id: "csv-date-filter",
    title: "Filter Sales by Date Range",
    source: "Console Lab",
    difficulty: "mid",
    timeMinutes: 25,
    prompt: "CSV Date,Product,Amount. Args start/end date. Print total sales in range.",
    constraints: ["DateTime compare", "Sum"],
    think: [
      ["Bounds", "Parse start/end once."],
      ["Filter", "Where date >= start && date <= end."],
      ["Sum", "Sum amounts."],
    ],
    skeleton: ["parse range", "read filter", "sum print"],
    criteria: [
      { id: "date", label: "Date filtering", hint: "DateTime compare", test: hasAny(/DateTime/i, />=/, /<=/), weight: 2 },
      { id: "sum", label: "Total sum", hint: "Sum()", test: has(/Sum/i), weight: 1 },
    ],
    mistakes: ["Inclusive/exclusive boundary wrong", "Culture date parse"],
  }),
  c({
    id: "nested-json-sum",
    title: "Sum All Numbers in Nested JSON",
    source: "Console Lab",
    difficulty: "senior",
    timeMinutes: 35,
    prompt: "Recursively walk JSON object/array, sum every numeric value, print total.",
    constraints: ["JsonElement recursion", "No Newtonsoft"],
    think: [
      ["Recursive fn", "Switch on ValueKind: Number add, Object iterate props, Array iterate items."],
      ["Base", "Null/string/bool → 0 contribution."],
    ],
    skeleton: ["parse doc", "recursive SumElement", "print total"],
    criteria: [
      { id: "recurse", label: "Recursion/walk", hint: "function calls self or stack", test: hasAny(/void Sum|int Sum|SumElement/i, /EnumerateObject/i, /EnumerateArray/i), weight: 2 },
      { id: "json", label: "JsonElement", hint: "ValueKind", test: has(/JsonElement/i), weight: 1 },
    ],
    mistakes: ["Only top-level numbers", "Stack overflow on deep mock"],
  }),
  c({
    id: "http-retry",
    title: "HTTP GET with 3 Retries",
    source: "Console Lab",
    difficulty: "mid",
    timeMinutes: 25,
    prompt: "GET URL, retry up to 3 times on failure with 1s delay, then print body or error.",
    constraints: ["HttpClient", "Task.Delay"],
    think: [
      ["Loop", "for attempt 1..3 try GET."],
      ["Catch", "On fail delay and retry."],
      ["Exit", "Print success or final error."],
    ],
    skeleton: ["retry loop", "try GetStringAsync", "Delay on fail", "print"],
    criteria: [
      { id: "retry", label: "Retry loop", hint: "for 3 attempts", test: hasAny(/for\s*\(.*3/, /retry/i, /attempt/i), weight: 2 },
      { id: "delay", label: "Delay between retries", hint: "Task.Delay", test: has(/Task\.Delay/i), weight: 1 },
      { id: "http", label: "HttpClient", hint: "", test: has(/HttpClient/i), weight: 1 },
    ],
    mistakes: ["Retry on 404 when shouldn't", "No delay thundering herd"],
  }),
  c({
    id: "inventory-reorder",
    title: "Products Below Reorder Level",
    source: "Console Lab",
    difficulty: "junior",
    timeMinutes: 20,
    prompt: "CSV Product,Stock,ReorderLevel. Print products where Stock < ReorderLevel.",
    constraints: ["Filter", "Simple parse"],
    think: [
      ["Parse ints", "Stock and ReorderLevel."],
      ["Filter", "Where stock < reorder."],
      ["Print", "Product names."],
    ],
    skeleton: ["read csv", "parse ints", "filter", "print"],
    criteria: [
      { id: "filter", label: "Compare stock vs reorder", hint: "< Reorder", test: hasAny(/</, /Reorder/i), weight: 2 },
      { id: "parse", label: "Parse numbers", hint: "TryParse/int.Parse", test: hasAny(/TryParse/i, /int\.Parse/i), weight: 1 },
    ],
    mistakes: ["<= vs < wrong", "String compare on numbers"],
  }),
  c({
    id: "student-grade-stats",
    title: "Min / Max / Avg Grade by Class",
    source: "Console Lab",
    difficulty: "mid",
    timeMinutes: 30,
    prompt: "CSV Class,Student,Grade. Per class print min, max, average grade.",
    constraints: ["GroupBy", "LINQ stats"],
    think: [
      ["Group", "GroupBy class name."],
      ["Stats", "Min, Max, Average on Grade."],
      ["Print", "One line per class."],
    ],
    skeleton: ["read", "group class", "min max avg", "print"],
    criteria: [
      { id: "group", label: "GroupBy class", hint: "", test: has(/GroupBy/i), weight: 1 },
      { id: "stats", label: "Min Max Average", hint: "", test: hasAny(/\.Min/i, /\.Max/i, /\.Average/i), weight: 2 },
    ],
    mistakes: ["Stats on wrong column", "Average as int"],
  }),
  c({
    id: "url-domain-count",
    title: "Count URLs by Domain",
    source: "Console Lab",
    difficulty: "mid",
    timeMinutes: 25,
    prompt: "File of URLs one per line. Count by host/domain, print top 10.",
    constraints: ["Uri class or string parse"],
    think: [
      ["Parse host", "Uri.TryCreate → Host, or manual after ://"],
      ["Count", "Dictionary host→count."],
      ["Top 10", "Sort desc."],
    ],
    skeleton: ["read urls", "extract host", "count", "top 10"],
    criteria: [
      { id: "uri", label: "Extracts domain/host", hint: "Uri or Host", test: hasAny(/Uri/i, /Host/i, /\/\//), weight: 2 },
      { id: "count", label: "Counts", hint: "Dictionary", test: has(/Dictionary/i), weight: 1 },
    ],
    mistakes: ["Including path in key", "Not handling invalid URLs"],
  }),
  c({
    id: "binary-search-stdin",
    title: "Binary Search on Sorted Array",
    source: "Console Lab",
    difficulty: "mid",
    timeMinutes: 25,
    prompt: "Read sorted ints and target. Print index or -1.",
    constraints: ["O(log n)", "No LINQ search"],
    think: [
      ["Bounds", "low=0, high=n-1."],
      ["Loop", "While low<=high, mid, compare, narrow."],
      ["Return", "Index or -1."],
    ],
    skeleton: ["read array + target", "low high mid", "while loop", "print index"],
    criteria: [
      { id: "binary", label: "Binary search pattern", hint: "mid low high", test: hasAny(/mid/i, /low/i, /high/i), weight: 2 },
      { id: "while", label: "While loop", hint: "", test: has(/while\s*\(/i), weight: 1 },
    ],
    mistakes: ["Off-by-one on mid", "Using linear search silently"],
  }),
  c({
    id: "matrix-spiral",
    title: "Print Matrix in Spiral Order",
    source: "Console Lab",
    difficulty: "senior",
    timeMinutes: 35,
    prompt: "2D int matrix from stdin or hardcoded. Print elements in spiral order.",
    constraints: ["Layer boundaries", "Console output"],
    think: [
      ["Bounds", "top, bottom, left, right indices."],
      ["Directions", "Right along top, down right col, left bottom, up left col, shrink bounds."],
      ["Stop", "When top>bottom or left>right."],
    ],
    skeleton: ["matrix", "top/bottom/left/right", "4 directions loop", "print"],
    criteria: [
      { id: "bounds", label: "Boundary variables", hint: "top bottom left right", test: hasAny(/top/i, /bottom/i, /left/i, /right/i), weight: 2 },
      { id: "loop", label: "Layer loop", hint: "while top<=bottom", test: has(/while\s*\(/i), weight: 1 },
    ],
    mistakes: ["Duplicate center cell", "Not shrinking bounds"],
  }),
  c({
    id: "env-config-parser",
    title: "Parse KEY=VALUE Config Lines",
    source: "Console Lab",
    difficulty: "junior",
    timeMinutes: 20,
    prompt: "Read config file lines KEY=VALUE. Skip blanks and # comments. Print keys sorted.",
    constraints: ["Split first =", "Dictionary"],
    think: [
      ["Skip", "Empty lines and lines starting #."],
      ["Split", "IndexOf('=') split once (values may contain =)."],
      ["Store", "Dictionary key→value, print keys sorted."],
    ],
    skeleton: ["read lines", "skip comments", "split =", "dict", "sort keys print"],
    criteria: [
      { id: "skip", label: "Skips comments/blank", hint: "StartsWith #", test: hasAny(/#/i, /IsNullOrWhiteSpace/i), weight: 1 },
      { id: "split", label: "KEY=VALUE parse", hint: "Split or IndexOf =", test: hasAny(/=/, /Split/i), weight: 2 },
    ],
    mistakes: ["Split on all = breaks values with ="],
  }),
  c({
    id: "api-status-counter",
    title: "HTTP Status Code Counter from Log",
    source: "Console Lab",
    difficulty: "mid",
    timeMinutes: 25,
    prompt: "Log format: ... STATUS ... Extract HTTP status codes (3 digits), count each, print sorted by code.",
    constraints: ["Regex or split", "Dictionary"],
    think: [
      ["Extract", "Regex \\b\\d{3}\\b or known column index."],
      ["Count", "Dictionary status→count."],
      ["Sort", "OrderBy status code."],
    ],
    skeleton: ["read log", "extract status", "count", "sort print"],
    criteria: [
      { id: "extract", label: "Extracts status code", hint: "Regex or parse", test: hasAny(/Regex/i, /\d{3}/i, /status/i), weight: 2 },
      { id: "count", label: "Counts", hint: "Dictionary", test: has(/Dictionary/i), weight: 1 },
    ],
    mistakes: ["Matching wrong 3-digit numbers"],
  }),
  c({
    id: "csv-pivot-category-month",
    title: "Pivot — Count by Category and Month",
    source: "Console Lab",
    difficulty: "senior",
    timeMinutes: 35,
    prompt: "CSV Date,Category. Count rows per (Month-Year, Category), print like space-news format.",
    constraints: ["Same pattern as space news", "DateTime"],
    think: [
      ["Same as space news", "Reuse grouping mental model: month name, year, category key."],
      ["Count increment", "Dictionary composite key."],
      ["Sort chronologically", "Year then month number."],
    ],
    skeleton: ["read csv", "parse date", "key month-year+category", "count sort print"],
    criteria: [
      { id: "date", label: "Date parsing", hint: "DateTime", test: has(/DateTime/i), weight: 1 },
      { id: "group", label: "Composite grouping", hint: "Dictionary/GroupBy", test: hasAny(/Dictionary/i, /GroupBy/i), weight: 2 },
      { id: "month", label: "Month in output", hint: "Month name", test: hasAny(/MMMM/i, /Month/i), weight: 1 },
    ],
    mistakes: ["Only grouping by category", "Wrong date format"],
  }),
  c({
    id: "stdin-line-stats",
    title: "Stdin Line Stats — Words and Lines",
    source: "Console Lab",
    difficulty: "junior",
    timeMinutes: 15,
    prompt: "Read stdin until empty line. Print total lines, total words, longest line length.",
    constraints: ["Console.ReadLine loop", "No files"],
    think: [
      ["Loop", "While ReadLine not null/empty."],
      ["Words", "Split whitespace, count."],
      ["Track max", "Longest line char count."],
    ],
    skeleton: ["while ReadLine", "line++ words+=", "track max len", "print 3 stats"],
    criteria: [
      { id: "read", label: "Reads stdin", hint: "Console.ReadLine", test: has(/ReadLine/i), weight: 2 },
      { id: "count", label: "Counts lines/words", hint: "counters", test: hasAny(/lines/i, /words/i, /\+\+/), weight: 1 },
    ],
    mistakes: ["Not handling empty stdin", "Counting chars as words"],
  }),
];
