import type { SystemDesignChallenge, ThoughtStep } from "../../types/consoleLab";
import { has, hasAny } from "../../utils/consoleLabEvaluator";

function steps(...items: [string, string][]): ThoughtStep[] {
  return items.map(([title, body], i) => ({ step: i + 1, title, body }));
}

function sd(
  partial: Omit<
    SystemDesignChallenge,
    "thoughtProcess" | "skeleton" | "criteria" | "commonMistakes"
  > & {
    think: [string, string][];
    skeleton: string[];
    criteria: SystemDesignChallenge["criteria"];
    mistakes: string[];
  },
): SystemDesignChallenge {
  return {
    ...partial,
    thoughtProcess: steps(...partial.think),
    skeleton: partial.skeleton,
    criteria: partial.criteria,
    commonMistakes: partial.mistakes,
  };
}

const sectionChecks = (sections: string[]) =>
  sections.map((s) => ({
    id: `section-${s.toLowerCase()}`,
    label: `Covers "${s}" section`,
    hint: `Include a heading or paragraph for ${s}.`,
    test: hasAny(new RegExp(s, "i"), new RegExp(s.replace(/\s+/g, ""), "i")),
    weight: 1,
  }));

export const SYSTEM_DESIGN_CHALLENGES: SystemDesignChallenge[] = [
  sd({
    id: "cinema-booking-rest",
    title: "Cinema Booking System (REST + PostgreSQL)",
    source: "Investec",
    difficulty: "senior",
    timeMinutes: 25,
    prompt: "Design cinema booking: register, pick location/show/seats, book, cancel. No payments, no ticket tiers.",
    functionalRequirements: [
      "Register account",
      "Choose cinema, show, seats",
      "Create and cancel booking",
    ],
    outOfScope: ["Payments", "Adult/child tickets", "VIP pricing"],
    requiredSections: ["tech", "database", "apis", "security", "other considerations"],
    think: [
      ["Clarify", "One seat once per showtime. Cancel before show starts."],
      ["Data model", "users, cinemas, screens, showtimes, seats, bookings, booking_seats."],
      ["Concurrency", "UNIQUE(showtime_id, seat_id) + transaction or FOR UPDATE."],
      ["APIs", "REST: list shows, seat map, POST booking, DELETE cancel."],
      ["Security", "JWT auth, users only own bookings, HTTPS, audit log."],
    ],
    skeleton: ["tech stack", "ER tables + unique constraint", "REST endpoints", "auth", "concurrency + scale notes"],
    criteria: [
      ...sectionChecks(["tech", "database", "apis", "security", "other"]),
      {
        id: "seat-uniqueness",
        label: "Prevents double booking",
        hint: "Unique constraint, lock, or optimistic concurrency.",
        test: hasAny(/unique/i, /lock/i, /transaction/i, /for update/i),
        weight: 2,
      },
      {
        id: "cancel",
        label: "Cancellation flow",
        hint: "Release seats on cancel.",
        test: hasAny(/cancel/i, /release/i),
        weight: 1,
      },
    ],
    mistakes: ["No seat concurrency story", "Payment scope creep", "Missing auth on book"],
  }),
  sd({
    id: "cinema-booking-events",
    title: "Cinema Booking (Event-Driven + Redis Holds)",
    source: "Investec",
    difficulty: "lead",
    timeMinutes: 30,
    prompt: "Same cinema booking — design for peak load with Redis seat holds and event bus.",
    functionalRequirements: ["Book/cancel seats", "Peak premiere traffic"],
    requiredSections: ["tech", "database", "apis", "security", "other considerations"],
    think: [
      ["Hold pattern", "Redis SET NX EX on seat during selection."],
      ["Confirm", "DB transaction on confirm; release holds."],
      ["Events", "BookingConfirmed → email/analytics via outbox."],
      ["Failure", "Redis down → fall back to DB-only locking."],
    ],
    skeleton: ["Redis hold TTL", "DB truth", "outbox events", "API flow", "degrade path"],
    criteria: [
      ...sectionChecks(["tech", "database", "apis", "security", "other"]),
      {
        id: "redis",
        label: "Redis or cache holds",
        hint: "Temporary seat reservation.",
        test: hasAny(/redis/i, /hold/i, /ttl/i),
        weight: 2,
      },
      {
        id: "events",
        label: "Event-driven aspect",
        hint: "Queue, outbox, pub/sub.",
        test: hasAny(/event/i, /queue/i, /outbox/i, /message/i),
        weight: 1,
      },
    ],
    mistakes: ["Hold without expiry", "No compensation if confirm fails"],
  }),
  sd({
    id: "url-shortener",
    title: "URL Shortener (bit.ly)",
    source: "Console Lab",
    difficulty: "senior",
    timeMinutes: 25,
    prompt: "Design short URL service: create short link, redirect, analytics click count.",
    functionalRequirements: ["Shorten URL", "Redirect", "Optional analytics"],
    requiredSections: ["tech", "database", "apis", "security", "other considerations"],
    think: [
      ["ID generation", "Base62 counter or hash + collision check."],
      ["Redirect", "HTTP 301/302 fast path — cache hot links."],
      ["Scale", "Read-heavy — CDN/cache, write to DB."],
    ],
    skeleton: ["API POST /shorten GET /:id", "DB mapping", "cache", "rate limit"],
    criteria: [
      ...sectionChecks(["tech", "database", "apis", "security"]),
      { id: "redirect", label: "Redirect flow", hint: "302/301", test: hasAny(/redirect/i, /302/i, /301/i), weight: 1 },
      { id: "encode", label: "Short code strategy", hint: "base62/hash", test: hasAny(/base62/i, /hash/i, /short/i), weight: 1 },
    ],
    mistakes: ["No collision plan", "Redirect hits DB every time"],
  }),
  sd({
    id: "paste-bin",
    title: "Paste Bin",
    source: "Console Lab",
    difficulty: "mid",
    timeMinutes: 20,
    prompt: "Store text snippets with optional expiry, retrieve by ID.",
    functionalRequirements: ["Create paste", "Read by id", "TTL expiry"],
    requiredSections: ["tech", "database", "apis", "security", "other considerations"],
    think: [
      ["Storage", "Object store or DB blob for content."],
      ["TTL", "Redis expiry or scheduled cleanup job."],
      ["ID", "UUID or random slug."],
    ],
    skeleton: ["POST paste", "GET /:id", "TTL job", "size limits"],
    criteria: sectionChecks(["tech", "database", "apis", "security"]),
    mistakes: ["No max size limit", "Predictable IDs leaking data"],
  }),
  sd({
    id: "chat-messaging",
    title: "Real-Time Chat (WhatsApp-lite)",
    source: "Console Lab",
    difficulty: "senior",
    timeMinutes: 30,
    prompt: "1:1 and group messaging with delivery/read receipts.",
    functionalRequirements: ["Send/receive", "Groups", "Online presence optional"],
    requiredSections: ["tech", "database", "apis", "security", "other considerations"],
    think: [
      ["Transport", "WebSockets or SSE for push."],
      ["Storage", "Messages partitioned by conversation_id + time."],
      ["Delivery", "At-least-once + client dedupe by message id."],
    ],
    skeleton: ["WS gateway", "message store", "conversation model", "receipts"],
    criteria: [
      ...sectionChecks(["tech", "database", "apis", "security"]),
      { id: "realtime", label: "Real-time channel", hint: "WebSocket/SSE", test: hasAny(/websocket/i, /sse/i, /real.?time/i), weight: 2 },
    ],
    mistakes: ["Polling only at scale", "No message ordering story"],
  }),
  sd({
    id: "ride-hailing",
    title: "Ride Hailing (Uber-lite)",
    source: "Console Lab",
    difficulty: "lead",
    timeMinutes: 35,
    prompt: "Match riders to drivers, track trip, complete ride.",
    functionalRequirements: ["Request ride", "Driver accept", "GPS track", "Complete"],
    requiredSections: ["tech", "database", "apis", "security", "other considerations"],
    think: [
      ["Matching", "Geo index drivers near pickup — Redis GEO or PostGIS."],
      ["State machine", "Requested→Accepted→InProgress→Completed."],
      ["Location", "Driver pings every N seconds."],
    ],
    skeleton: ["geo match", "trip state machine", "location stream", "APIs"],
    criteria: [
      ...sectionChecks(["tech", "database", "apis"]),
      { id: "geo", label: "Geolocation matching", hint: "geo hash/index", test: hasAny(/geo/i, /location/i, /gps/i), weight: 2 },
    ],
    mistakes: ["No state machine", "Matching O(all drivers)"],
  }),
  sd({
    id: "news-feed",
    title: "Social News Feed",
    source: "Console Lab",
    difficulty: "senior",
    timeMinutes: 30,
    prompt: "User home feed from followed accounts, chronological or ranked.",
    functionalRequirements: ["Post", "Follow", "Read feed"],
    requiredSections: ["tech", "database", "apis", "security", "other considerations"],
    think: [
      ["Fan-out", "Push on write vs pull on read — tradeoffs."],
      ["Cache", "Celebrity problem — hybrid fan-out."],
      ["Pagination", "Cursor-based by post id/time."],
    ],
    skeleton: ["post table", "follow graph", "feed fan-out", "cache"],
    criteria: [
      ...sectionChecks(["tech", "database", "apis"]),
      { id: "fanout", label: "Feed generation strategy", hint: "fan-out on write/read", test: hasAny(/fan.?out/i, /feed/i, /timeline/i), weight: 2 },
    ],
    mistakes: ["Only pull model at scale", "Offset pagination deep pages"],
  }),
  sd({
    id: "video-streaming",
    title: "Video Streaming (Netflix-lite)",
    source: "Console Lab",
    difficulty: "lead",
    timeMinutes: 35,
    prompt: "Upload, encode, stream video to users with adaptive bitrate.",
    functionalRequirements: ["Catalog", "Stream playback", "Resume position"],
    requiredSections: ["tech", "database", "apis", "security", "other considerations"],
    think: [
      ["Storage", "Blob store + CDN for segments."],
      ["Encoding", "Async pipeline HLS/DASH chunks."],
      ["Playback", "Signed URLs, resume bookmark in DB."],
    ],
    skeleton: ["blob+CDN", "encode queue", "manifest", "signed URL"],
    criteria: [
      ...sectionChecks(["tech", "database", "apis"]),
      { id: "cdn", label: "CDN or blob storage", hint: "", test: hasAny(/cdn/i, /blob/i, /s3/i), weight: 2 },
    ],
    mistakes: ["Serving video from app server", "No transcoding pipeline"],
  }),
  sd({
    id: "rate-limiter",
    title: "Distributed Rate Limiter",
    source: "Console Lab",
    difficulty: "senior",
    timeMinutes: 25,
    prompt: "Limit API requests per user/IP across many servers.",
    functionalRequirements: ["Configurable limits", "Distributed correctness"],
    requiredSections: ["tech", "database", "apis", "security", "other considerations"],
    think: [
      ["Algorithm", "Token bucket or sliding window in Redis."],
      ["Key", "user id or IP per endpoint."],
      ["Response", "429 + Retry-After header."],
    ],
    skeleton: ["Redis counter", "window/bucket", "middleware", "429"],
    criteria: [
      ...sectionChecks(["tech", "apis"]),
      { id: "redis", label: "Shared store", hint: "Redis", test: has(/redis/i), weight: 1 },
      { id: "429", label: "Rate limit response", hint: "429", test: hasAny(/429/i, /rate limit/i), weight: 1 },
    ],
    mistakes: ["In-memory only per server", "Race without atomic INCR"],
  }),
  sd({
    id: "distributed-cache",
    title: "Distributed Cache",
    source: "Console Lab",
    difficulty: "senior",
    timeMinutes: 25,
    prompt: "Design cache layer in front of DB with eviction and invalidation.",
    functionalRequirements: ["Get/set", "TTL", "Invalidate on write"],
    requiredSections: ["tech", "database", "apis", "security", "other considerations"],
    think: [
      ["Pattern", "Cache-aside: read miss loads DB, write updates DB then evict."],
      ["Eviction", "LRU/TTL."],
      ["Stampede", "Single-flight lock on hot miss."],
    ],
    skeleton: ["cache-aside", "TTL", "invalidation", "stampede protection"],
    criteria: [
      ...sectionChecks(["tech", "other"]),
      { id: "cache-aside", label: "Caching pattern", hint: "cache-aside/write-through", test: hasAny(/cache/i, /ttl/i, /evict/i), weight: 2 },
    ],
    mistakes: ["No invalidation strategy", "Cache stampede ignored"],
  }),
  sd({
    id: "payment-wallet",
    title: "Digital Wallet (no PCI deep-dive)",
    source: "Console Lab",
    difficulty: "lead",
    timeMinutes: 30,
    prompt: "User balance, credit/debit ledger, transfer between users.",
    functionalRequirements: ["Deposit", "Transfer", "Balance query"],
    requiredSections: ["tech", "database", "apis", "security", "other considerations"],
    think: [
      ["Ledger", "Immutable transactions; balance = sum or snapshot + ledger."],
      ["Transfer", "Single DB transaction debits A credits B."],
      ["Idempotency", "Idempotency-Key on transfers."],
    ],
    skeleton: ["ledger table", "ACID transfer", "idempotency", "audit"],
    criteria: [
      ...sectionChecks(["tech", "database", "apis", "security"]),
      { id: "ledger", label: "Ledger/transaction model", hint: "", test: hasAny(/ledger/i, /transaction/i, /idempotent/i), weight: 2 },
    ],
    mistakes: ["Updating balance without ledger", "Double spend on retry"],
  }),
  sd({
    id: "food-delivery",
    title: "Food Delivery Platform",
    source: "Console Lab",
    difficulty: "senior",
    timeMinutes: 30,
    prompt: "Order food from restaurant, track delivery driver.",
    functionalRequirements: ["Browse menu", "Order", "Track delivery"],
    requiredSections: ["tech", "database", "apis", "security", "other considerations"],
    think: [
      ["Actors", "Customer, restaurant, driver — separate services or modules."],
      ["Order state", "Placed→Accepted→Preparing→OutForDelivery→Delivered."],
      ["Real-time", "Driver location to customer."],
    ],
    skeleton: ["order FSM", "menu service", "driver tracking", "notifications"],
    criteria: sectionChecks(["tech", "database", "apis", "security"]),
    mistakes: ["No order state machine", "Menu coupled to orders table"],
  }),
  sd({
    id: "hotel-booking",
    title: "Hotel Room Booking",
    source: "Console Lab",
    difficulty: "senior",
    timeMinutes: 25,
    prompt: "Search availability by date range, book room, cancel.",
    functionalRequirements: ["Search", "Book date range", "Cancel"],
    requiredSections: ["tech", "database", "apis", "security", "other considerations"],
    think: [
      ["Availability", "Room-night inventory per date — similar to seat problem across dates."],
      ["Booking", "Transaction locks room-nights."],
      ["Search", "Index hotel+date range query."],
    ],
    skeleton: ["room_nights table", "date range search", "book transaction", "cancel policy"],
    criteria: [
      ...sectionChecks(["tech", "database", "apis"]),
      { id: "availability", label: "Availability model", hint: "room-nights", test: hasAny(/avail/i, /inventory/i, /date/i), weight: 2 },
    ],
    mistakes: ["Double book same room-night", "No timezone on dates"],
  }),
  sd({
    id: "parking-lot",
    title: "Parking Lot System",
    source: "Console Lab",
    difficulty: "mid",
    timeMinutes: 20,
    prompt: "Multi-floor parking, assign spot on entry, free on exit, calculate fee.",
    functionalRequirements: ["Park", "Exit", "Fee by duration"],
    requiredSections: ["tech", "database", "apis", "security", "other considerations"],
    think: [
      ["Spots", "Enum spot types compact/large/handicap."],
      ["Assignment", "Find first free matching vehicle type."],
      ["Ticket", "Entry timestamp, exit computes fee."],
    ],
    skeleton: ["spot occupancy", "entry ticket", "fee calc", "gate API"],
    criteria: sectionChecks(["tech", "database", "apis"]),
    mistakes: ["No spot type matching", "Lost ticket edge case ignored"],
  }),
  sd({
    id: "ticket-master",
    title: "Concert Ticket Sales",
    source: "Console Lab",
    difficulty: "senior",
    timeMinutes: 30,
    prompt: "High-demand ticket sale — similar to cinema but with queue/waiting room.",
    functionalRequirements: ["Browse events", "Purchase tickets", "High concurrency"],
    requiredSections: ["tech", "database", "apis", "security", "other considerations"],
    think: [
      ["Queue", "Virtual waiting room before sale opens."],
      ["Inventory", "Seat map like cinema + payment scope if asked."],
      ["Bot protection", "Rate limit + CAPTCHA at door."],
    ],
    skeleton: ["waiting room", "seat lock", "checkout", "anti-bot"],
    criteria: [
      ...sectionChecks(["tech", "database", "apis", "security"]),
      { id: "queue", label: "Queue or concurrency control", hint: "", test: hasAny(/queue/i, /waiting/i, /lock/i), weight: 2 },
    ],
    mistakes: ["Direct to DB on sale open", "No idempotent purchase"],
  }),
  sd({
    id: "notification-system",
    title: "Push Notification System",
    source: "Console Lab",
    difficulty: "senior",
    timeMinutes: 25,
    prompt: "Send email/SMS/push to millions of users from events.",
    functionalRequirements: ["Multi-channel", "Templates", "Retry"],
    requiredSections: ["tech", "database", "apis", "security", "other considerations"],
    think: [
      ["Queue", "Producers enqueue, workers send via providers."],
      ["Retry", "Dead letter queue on failure."],
      ["Preferences", "User opt-out per channel."],
    ],
    skeleton: ["event queue", "workers", "provider adapters", "DLQ"],
    criteria: [
      ...sectionChecks(["tech", "database", "apis"]),
      { id: "queue", label: "Async queue", hint: "", test: hasAny(/queue/i, /worker/i, /async/i), weight: 2 },
    ],
    mistakes: ["Synchronous send in API request", "No retry/DLQ"],
  }),
  sd({
    id: "file-storage",
    title: "File Storage (Dropbox-lite)",
    source: "Console Lab",
    difficulty: "senior",
    timeMinutes: 30,
    prompt: "Upload/sync files, versioning, share links.",
    functionalRequirements: ["Upload", "Download", "Sync folders"],
    requiredSections: ["tech", "database", "apis", "security", "other considerations"],
    think: [
      ["Blob", "Content-addressed chunks in object storage."],
      ["Metadata", "File tree in DB per user."],
      ["Sync", "Delta upload by hash/chunk."],
    ],
    skeleton: ["blob store", "metadata DB", "chunking", "share links"],
    criteria: [
      ...sectionChecks(["tech", "database", "apis", "security"]),
      { id: "blob", label: "Object/blob storage", hint: "", test: hasAny(/blob/i, /s3/i, /object/i, /storage/i), weight: 1 },
    ],
    mistakes: ["Store files in Postgres rows", "No chunk dedup"],
  }),
  sd({
    id: "search-autocomplete",
    title: "Search Autocomplete",
    source: "Console Lab",
    difficulty: "senior",
    timeMinutes: 25,
    prompt: "Typeahead suggestions for search box, low latency.",
    functionalRequirements: ["Prefix search", "Top K suggestions"],
    requiredSections: ["tech", "database", "apis", "security", "other considerations"],
    think: [
      ["Structure", "Trie or Elasticsearch prefix query."],
      ["Ranking", "By popularity/frequency."],
      ["Cache", "Hot prefixes in Redis."],
    ],
    skeleton: ["trie or ES", "ranking", "cache hot prefixes", "API"],
    criteria: [
      ...sectionChecks(["tech", "database", "apis"]),
      { id: "prefix", label: "Prefix search approach", hint: "trie/prefix", test: hasAny(/trie/i, /prefix/i, /autocomplete/i, /elastic/i), weight: 2 },
    ],
    mistakes: ["Full table scan LIKE '%x'", "No ranking"],
  }),
  sd({
    id: "leaderboard",
    title: "Gaming Leaderboard",
    source: "Console Lab",
    difficulty: "mid",
    timeMinutes: 20,
    prompt: "Global and friends leaderboard, update score in real time.",
    functionalRequirements: ["Submit score", "Top N global", "Friends rank"],
    requiredSections: ["tech", "database", "apis", "security", "other considerations"],
    think: [
      ["Store", "Redis sorted set ZADD for O(log N) rank."],
      ["Friends", "Filter friend ids or separate zset per user."],
      ["Scale", "Shard leaderboard by game/season."],
    ],
    skeleton: ["Redis ZSET", "submit score API", "top N query", "friends filter"],
    criteria: [
      ...sectionChecks(["tech", "database", "apis"]),
      { id: "rank", label: "Ranking structure", hint: "sorted set/rank", test: hasAny(/sorted/i, /rank/i, /leaderboard/i, /zadd/i), weight: 2 },
    ],
    mistakes: ["Sort full table in SQL every read"],
  }),
  sd({
    id: "email-service",
    title: "Transactional Email Service",
    source: "Console Lab",
    difficulty: "senior",
    timeMinutes: 25,
    prompt: "API to send templated emails at scale with bounce handling.",
    functionalRequirements: ["Send API", "Templates", "Bounces"],
    requiredSections: ["tech", "database", "apis", "security", "other considerations"],
    think: [
      ["Queue", "API enqueues, workers call SES/SendGrid."],
      ["Templates", "Store template id + variables."],
      ["Webhooks", "Bounce/complaint updates suppression list."],
    ],
    skeleton: ["queue", "template engine", "provider", "suppression list"],
    criteria: sectionChecks(["tech", "database", "apis", "security"]),
    mistakes: ["Send inline in request", "No bounce handling"],
  }),
  sd({
    id: "analytics-pipeline",
    title: "Click Analytics Pipeline",
    source: "Console Lab",
    difficulty: "lead",
    timeMinutes: 30,
    prompt: "Collect click events, aggregate DAU/page views, dashboard queries.",
    functionalRequirements: ["Ingest events", "Aggregate metrics", "Query dashboard"],
    requiredSections: ["tech", "database", "apis", "security", "other considerations"],
    think: [
      ["Ingest", "Kafka/event hub → stream processors."],
      ["Store", "Raw in data lake, aggregates in OLAP/Postgres rollups."],
      ["Late data", "Windowed aggregation with watermark."],
    ],
    skeleton: ["event ingest", "stream/batch", "rollup tables", "query API"],
    criteria: [
      ...sectionChecks(["tech", "database", "apis"]),
      { id: "stream", label: "Event pipeline", hint: "kafka/stream", test: hasAny(/kafka/i, /event/i, /stream/i, /pipeline/i), weight: 2 },
    ],
    mistakes: ["Write every click to single Postgres row", "No batching"],
  }),
  sd({
    id: "multi-tenant-saas",
    title: "Multi-Tenant SaaS",
    source: "Console Lab",
    difficulty: "lead",
    timeMinutes: 30,
    prompt: "Isolate customer data per tenant, shared app tier.",
    functionalRequirements: ["Tenant signup", "Data isolation", "Shared infra"],
    requiredSections: ["tech", "database", "apis", "security", "other considerations"],
    think: [
      ["Model", "Shared schema + tenant_id vs schema-per-tenant."],
      ["Auth", "JWT tenant claim, middleware filter every query."],
      ["Noisy neighbor", "Rate limits per tenant."],
    ],
    skeleton: ["tenant_id column", "RLS or filter", "auth claims", "isolation tradeoffs"],
    criteria: [
      ...sectionChecks(["tech", "database", "apis", "security"]),
      { id: "tenant", label: "Tenant isolation", hint: "tenant_id/RLS", test: hasAny(/tenant/i, /isol/i, /rls/i), weight: 2 },
    ],
    mistakes: ["Forgetting tenant filter on one query", "Wrong isolation model for compliance"],
  }),
  sd({
    id: "inventory-warehouse",
    title: "Warehouse Inventory System",
    source: "Console Lab",
    difficulty: "mid",
    timeMinutes: 25,
    prompt: "Track SKU stock across warehouses, reserve on order, ship decrement.",
    functionalRequirements: ["Stock levels", "Reserve", "Ship"],
    requiredSections: ["tech", "database", "apis", "security", "other considerations"],
    think: [
      ["Reserve", "available = on_hand - reserved."],
      ["Transaction", "Reserve in same TX as order create."],
      ["Concurrent", "Optimistic locking on SKU row."],
    ],
    skeleton: ["sku_warehouse qty", "reservation", "ship decrement", "locking"],
    criteria: sectionChecks(["tech", "database", "apis", "security"]),
    mistakes: ["Oversell without reservation", "Global stock only"],
  }),
  sd({
    id: "social-timeline",
    title: "Twitter Timeline (post tweet, follow, feed)",
    source: "Console Lab",
    difficulty: "senior",
    timeMinutes: 30,
    prompt: "Post 280 char tweets, follow users, home timeline.",
    functionalRequirements: ["Tweet", "Follow", "Timeline"],
    requiredSections: ["tech", "database", "apis", "security", "other considerations"],
    think: [
      ["Write path", "Insert tweet, fan-out to follower feeds if push model."],
      ["Read path", "Merge followees recent tweets — cache hot users."],
      ["Celebrities", "Pull model for millions of followers."],
    ],
    skeleton: ["tweets table", "follow graph", "fan-out/pull hybrid", "timeline cache"],
    criteria: sectionChecks(["tech", "database", "apis", "security"]),
    mistakes: ["Fan-out to 10M followers synchronously"],
  }),
  sd({
    id: "api-gateway",
    title: "API Gateway",
    source: "Console Lab",
    difficulty: "senior",
    timeMinutes: 25,
    prompt: "Single entry point: routing, auth, rate limit, logging.",
    functionalRequirements: ["Route to services", "Auth", "Rate limit"],
    requiredSections: ["tech", "database", "apis", "security", "other considerations"],
    think: [
      ["Cross-cutting", "JWT validate once at gateway."],
      ["Route", "Path prefix to service cluster."],
      ["Observability", "Correlation ID injected."],
    ],
    skeleton: ["gateway layer", "auth middleware", "route rules", "rate limit"],
    criteria: [
      ...sectionChecks(["tech", "apis", "security"]),
      { id: "gateway", label: "Gateway role", hint: "route/auth", test: hasAny(/gateway/i, /route/i, /proxy/i), weight: 2 },
    ],
    mistakes: ["Business logic in gateway", "No correlation ID"],
  }),
  sd({
    id: "logging-monitoring",
    title: "Centralized Logging & Monitoring",
    source: "Console Lab",
    difficulty: "senior",
    timeMinutes: 25,
    prompt: "Aggregate logs/metrics from 100 microservices, alert on errors.",
    functionalRequirements: ["Collect logs", "Search", "Alert"],
    requiredSections: ["tech", "database", "apis", "security", "other considerations"],
    think: [
      ["Logs", "Agent ships to ELK/Datadog, structured JSON."],
      ["Metrics", "Prometheus scrape, Grafana dashboards."],
      ["Alert", "Threshold on error rate SLO."],
    ],
    skeleton: ["log shipper", "index/search", "metrics", "alert rules"],
    criteria: sectionChecks(["tech", "database", "other"]),
    mistakes: ["Plain text unsearchable logs", "Alert on single error"],
  }),
  sd({
    id: "airline-booking",
    title: "Airline Seat Booking",
    source: "Console Lab",
    difficulty: "senior",
    timeMinutes: 30,
    prompt: "Book flight segment with seat, multi-leg optional, cancel policy.",
    functionalRequirements: ["Search flights", "Book seat", "Cancel"],
    requiredSections: ["tech", "database", "apis", "security", "other considerations"],
    think: [
      ["Similar to cinema", "Segment + seat uniqueness."],
      ["PNR", "Booking reference grouping passengers."],
      ["Overbooking", "Optional airline-specific nuance."],
    ],
    skeleton: ["flights", "seats", "PNR", "cancel rules"],
    criteria: sectionChecks(["tech", "database", "apis", "security"]),
    mistakes: ["No segment/seat uniqueness", "Ignoring timezone"],
  }),
  sd({
    id: "ecommerce-cart",
    title: "E-Commerce Cart & Checkout",
    source: "Console Lab",
    difficulty: "senior",
    timeMinutes: 30,
    prompt: "Cart, inventory check, checkout (payment out of scope optional).",
    functionalRequirements: ["Add to cart", "Update qty", "Checkout reserve stock"],
    requiredSections: ["tech", "database", "apis", "security", "other considerations"],
    think: [
      ["Cart", "Redis or DB cart lines keyed by user/session."],
      ["Checkout", "Reserve inventory in transaction."],
      ["Expiry", "Cart TTL abandon cleanup."],
    ],
    skeleton: ["cart store", "inventory check", "checkout TX", "cart TTL"],
    criteria: sectionChecks(["tech", "database", "apis", "security"]),
    mistakes: ["No inventory reservation", "Cart lost on logout edge case"],
  }),
  sd({
    id: "weather-aggregator",
    title: "Weather API Aggregator",
    source: "Console Lab",
    difficulty: "mid",
    timeMinutes: 25,
    prompt: "Merge multiple weather providers, cache, serve unified API.",
    functionalRequirements: ["Fetch providers", "Cache", "Unified response"],
    requiredSections: ["tech", "database", "apis", "security", "other considerations"],
    think: [
      ["Cache", "TTL by location grid cell."],
      ["Fallback", "Provider B if A fails."],
      ["Normalize", "Map to common schema."],
    ],
    skeleton: ["provider adapters", "cache key geo", "fallback", "normalize"],
    criteria: sectionChecks(["tech", "database", "apis"]),
    mistakes: ["Hit providers every request", "No normalization"],
  }),
  sd({
    id: "library-system",
    title: "Library Book Lending",
    source: "Console Lab",
    difficulty: "mid",
    timeMinutes: 20,
    prompt: "Catalog books, borrow/return copies, fines optional.",
    functionalRequirements: ["Search catalog", "Borrow", "Return"],
    requiredSections: ["tech", "database", "apis", "security", "other considerations"],
    think: [
      ["Copies", "Book title vs physical copy barcode."],
      ["Loan", "User + copy + due date row."],
      ["Availability", "Count free copies per title."],
    ],
    skeleton: ["books/copies", "loan record", "due date", "return flow"],
    criteria: sectionChecks(["tech", "database", "apis", "security"]),
    mistakes: ["No copy-level tracking", "Double borrow same copy"],
  }),
  sd({
    id: "elevator-system",
    title: "Elevator Control System",
    source: "Console Lab",
    difficulty: "mid",
    timeMinutes: 20,
    prompt: "N elevators, M floors, optimize pickup — classic OO but design at system level.",
    functionalRequirements: ["Request up/down", "Dispatch elevator", "Safety"],
    requiredSections: ["tech", "database", "apis", "security", "other considerations"],
    think: [
      ["Dispatch", "Nearest car or SCAN algorithm."],
      ["State", "Each elevator: direction, current floor, queue."],
      ["Realtime", "Embedded controllers vs simulation API."],
    ],
    skeleton: ["elevator state", "request queue", "dispatch algo", "controller"],
    criteria: sectionChecks(["tech", "other"]),
    mistakes: ["No dispatch strategy mentioned", "Ignoring direction"],
  }),
];
